'use strict';
const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const escapeHTML = (s) => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = (n) => (Number(n || 0) / 100).toLocaleString('zh-CN', {minimumFractionDigits:2,maximumFractionDigits:2});
const time = (s) => s ? new Date(s).toLocaleString('zh-CN',{hour12:false}) : '—';
const names = {deposit:'充值',withdrawal:'提现',transfer:'转账',payment:'支付',refund:'退款'};
const pages = {overview:'运行总览',trades:'交易中心',accounts:'账户管理',ledger:'账务与对账',logs:'日志检索',resources:'资源与告警',loadtests:'并发压测',faults:'故障演练',diagnosis:'根因分析',knowledge:'运维知识库',assistant:'运维助手'};
let config = {}, accounts = [], current = 'overview', chatSession = sessionStorage.getItem('chat-session') || 'S-'+crypto.randomUUID();
sessionStorage.setItem('chat-session',chatSession);
let citations = new Map(), toastTimer;
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,6000)}
async function api(path, options={}){
  const headers = {'Content-Type':'application/json',...(options.headers||{})};
  const token=sessionStorage.getItem('finops-token'); if(token)headers.Authorization='Bearer '+token;
  let response;
  try{response=await fetch(path,{...options,headers})}catch(e){throw new Error('无法连接本地服务，请检查启动窗口。')}
  const body=await response.json();
  if(!response.ok){const error=new Error(body.message || (Array.isArray(body.detail)?body.detail.map(x=>x.msg).join('；'):body.detail) || '请求失败');error.body=body;error.status=response.status;throw error}
  $('#connection-error').hidden=true;
  return body;
}
const post=(path,body={})=>api(path,{method:'POST',body:JSON.stringify(body)});
function table(headers, rows){return rows.length?'<div class="table-wrap"><table><thead><tr>'+headers.map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(c=>'<td>'+c+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>':'<div class="empty">暂无记录</div>'}
function status(value){return '<span class="tag '+(value==='SUCCEEDED'?'':'red')+'">'+(value==='SUCCEEDED'?'已成功':'已拒绝')+'</span>'}
function shortId(id){return escapeHTML(id.length>18?id.slice(0,13)+'…':id)}
function traceButton(id){return '<button class="trace-link" data-trace="'+escapeHTML(id)+'" title="查看完整追踪日志">'+shortId(id)+'</button>'}
function accountName(id){return escapeHTML(accounts.find(a=>a.id===id)?.name || id)}
function tradeTable(rows){return table(['交易编号 / 时间','类型','金额','付款 → 收款','状态','追踪'],rows.map(t=>['<span class="code" title="'+escapeHTML(t.id)+'">'+shortId(t.id)+'</span><br><small>'+time(t.created_at)+'</small>',names[t.kind],'<span class="amount">¥ '+money(t.amount)+'</span>',accountName(t.source_id)+' → '+accountName(t.target_id),status(t.status),traceButton(t.trace_id)]))}
async function loadAccounts(){accounts=await api('/api/accounts');const regular=accounts.filter(a=>a.kind!=='system');['source','target'].forEach((key,index)=>{const select=$('#trade-'+key),old=select.value;select.innerHTML=regular.map(a=>'<option value="'+escapeHTML(a.id)+'">'+escapeHTML(a.name)+' · ¥'+money(a.balance)+'</option>').join('');select.value=regular.some(a=>a.id===old)?old:(regular[index]?.id||regular[0]?.id)});}
function renderChart(trend){if(!trend.length){$('#latency-chart').innerHTML='<div class="empty">发起一笔交易后，延迟观测将在这里出现。</div>';return}const max=Math.max(100,...trend.map(t=>t.duration_ms))*1.2;const points=trend.map((t,i)=>[45+i*650/Math.max(1,trend.length-1),180-t.duration_ms/max*150]);const line=points.map(p=>p.join(',')).join(' ');$('#latency-chart').innerHTML='<svg viewBox="0 0 730 215" role="img" aria-label="交易请求延迟图">'+[0,1,2,3].map(i=>'<line x1="45" x2="712" y1="'+(30+i*50)+'" y2="'+(30+i*50)+'" stroke="#edf1ef"/><text x="0" y="'+(34+i*50)+'">'+Math.round(max*(1-i/3))+'</text>').join('')+'<polygon fill="#edf5f0" points="45,180 '+line+' '+points.at(-1)[0]+',180"/><polyline fill="none" stroke="#3d8f73" stroke-width="2" points="'+line+'"/>'+points.map((p,i)=>'<circle cx="'+p[0]+'" cy="'+p[1]+'" r="3" fill="'+(trend[i].status>=500?'#be7756':'#3d8f73')+'"><title>'+trend[i].duration_ms+' ms</title></circle>').join('')+'<text x="45" y="208">较早请求</text><text x="659" y="208">最新请求</text></svg>'}
async function loadOverview(){const d=await api('/api/overview');const values=[['累计交易',d.trade_count,'笔','包含初始模拟充值'],['成功交易金额','¥ '+money(d.volume),'','各类成功交易金额合计'],['请求延迟 P95',d.p95_ms,'ms','最近 '+d.sample_count+' 次交易请求'],['活动演练',d.active_faults.length,'个','请求异常 '+d.request_error_count+' / '+d.sample_count]];$('#metrics').innerHTML=values.map((x,i)=>'<div class="metric"><div class="metric-label">'+x[0]+'<span>'+['↗','⇄','◷','ϟ'][i]+'</span></div><div class="metric-value">'+x[1]+'<small>'+x[2]+'</small></div><div class="metric-foot">'+x[3]+'</div></div>').join('');$('#recent-trades').innerHTML=tradeTable(d.recent_trades);renderChart(d.trend)}
async function loadTrades(q=''){$('#trade-list').innerHTML=tradeTable(await api('/api/trades?q='+encodeURIComponent(q)))}
async function loadAccountCards(){await loadAccounts();$('#account-list').innerHTML=accounts.map(a=>'<article class="account-card"><span class="tag '+(a.frozen?'amber':'')+'">'+({customer:'个人账户',merchant:'商户账户',system:'模拟清算账户'}[a.kind])+(a.frozen?' · 已冻结':'')+'</span><h2>'+escapeHTML(a.name)+'</h2><div class="code">'+escapeHTML(a.id)+'</div><div class="balance">¥ '+money(a.balance)+'</div><small>CNY · 当前账面余额</small>'+(a.kind!=='system'?'<br><button class="button secondary" data-freeze="'+escapeHTML(a.id)+'" data-value="'+(!a.frozen)+'">'+(a.frozen?'解冻账户':'冻结账户')+'</button>':'<p><small>清算对手方，允许负余额</small></p>')+'</article>').join('')}
async function loadEntries(){const rows=await api('/api/entries');$('#entry-list').innerHTML=table(['分录','交易编号','账户','借 / 贷','余额变动','时间'],rows.map(e=>[e.id,'<span class="code">'+escapeHTML(e.trade_id)+'</span>',accountName(e.account_id),e.side==="DEBIT"?'借记':'贷记','<span class="amount">'+(e.delta>0?'+':'')+money(e.delta)+'</span>',time(e.created_at)]))}
function logHTML(log){return '<article class="log-row"><div class="log-head"><span class="tag '+(log.level==='ERROR'?'red':log.level==='WARN'?'amber':'gray')+'">'+escapeHTML(log.level)+'</span><b>'+escapeHTML(log.event)+'</b><span>'+escapeHTML(log.service)+'</span><span>'+time(log.timestamp)+'</span><span>'+log.duration_ms+' ms</span></div><p>'+escapeHTML(log.message)+'</p><div class="code">TRACE '+escapeHTML(log.trace_id)+' · SPAN '+escapeHTML(log.span_id)+(log.transaction_id?' · '+escapeHTML(log.transaction_id):'')+'</div></article>'}
async function loadLogs(){const data=new FormData($('#log-search'));const query=new URLSearchParams([...data].filter(([,v])=>v));const logs=await api('/api/logs?'+query);$('#log-list').innerHTML=logs.map(logHTML).join('')||'<div class="card empty">没有匹配的日志</div>'}
async function loadFaults(){const d=await api('/api/faults');$('#fault-catalog').innerHTML=Object.entries(config.fault_catalog||{}).map(([key,f],i)=>'<article class="card fault-card"><span class="fault-number">0'+(i+1)+'</span><h2>'+escapeHTML(f.name)+'</h2><p>'+escapeHTML(f.description)+'</p><button class="button secondary" data-start-fault="'+key+'" '+(d.active.length?'disabled':'')+'>启动演练 →</button></article>').join('');$('#active-fault').innerHTML=d.active.map(f=>'<div class="notice"><b>演练中：'+escapeHTML(config.fault_catalog[f.kind].name)+'</b> · 将于 '+time(f.expires_at)+' 失效 <button class="button danger" data-stop-fault="'+f.id+'">立即停止</button> <a class="text-link" href="#trades">发送验证交易 →</a></div>').join('');$('#fault-history').innerHTML=table(['演练','开始时间','到期时间','状态'],d.history.map(f=>[escapeHTML(config.fault_catalog[f.kind]?.name||f.kind),time(f.started_at),time(f.expires_at),f.stopped_at?'已停止':new Date(f.expires_at)>new Date()?'进行中':'已到期']))}
function renderDiagnosis(d){$('#diagnosis-result').className='';$('#diagnosis-result').innerHTML='<article class="card"><span class="tag">分析了 '+d.scanned_records+' 条日志</span><h2 style="margin-top:18px">'+escapeHTML(d.summary)+'</h2><p class="muted">'+escapeHTML(d.method)+(d.truncated?' · 仅分析最近 500 条，请缩小范围':'')+'</p>'+d.candidates.map(c=>'<div class="candidate"><h3>'+escapeHTML(c.title)+'</h3><p>'+escapeHTML(c.explanation)+'</p><small>证据记录：'+c.evidence_ids.join(', ')+'</small><ul>'+c.next_steps.map(s=>'<li>'+escapeHTML(s)+'</li>').join('')+'</ul></div>').join('')+'</article><article class="card"><h2>证据时间线</h2><div class="evidence-list">'+(d.evidence.map(logHTML).join('')||'<div class="empty">未找到足够证据</div>')+'</div></article>'}
async function loadDocuments(){const docs=await api('/api/documents');$('#document-list').innerHTML=docs.map(d=>'<div class="doc-item"><span class="tag gray">v'+escapeHTML(d.version)+'</span><h3>'+escapeHTML(d.title)+'</h3><small>'+time(d.updated_at)+'</small><div class="button-row"><button class="button secondary" data-edit-doc="'+d.id+'">查看 / 编辑</button><button class="button danger" data-delete-doc="'+d.id+'">删除</button></div></div>').join('')||'<div class="empty">尚无手册</div>'}
function appendMessage(role,text,hits=[],mode=''){const welcome=$('.welcome');if(welcome)welcome.remove();const element=document.createElement('div');element.className='message '+role;const title=document.createElement('div');title.className='speaker';title.textContent=role==='user'?'你':mode==='rag'?'XIAOTAO助手 · 模型回答':'XIAOTAO助手 · 检索与证据';const body=document.createElement('div');body.className='body';body.textContent=text;element.append(title,body);if(hits.length){const list=document.createElement('div');list.className='citations';for(const h of hits){citations.set(h.chunk_id,h);const b=document.createElement('button');b.textContent=h.title+' · v'+h.version;b.dataset.citation=h.chunk_id;list.append(b)}element.append(list)}$('#chat-messages').append(element);$('#chat-messages').scrollTop=$('#chat-messages').scrollHeight}
async function loadChat(){if($('#chat-messages').dataset.loaded)return;const history=await api('/api/chat/'+chatSession);for(const turn of history){appendMessage('user',turn.question);appendMessage('assistant',turn.answer,turn.citations,turn.mode)}$('#chat-messages').dataset.loaded='true'}
async function refresh(){if(current==='overview')await loadOverview();else if(current==='trades'){await loadAccounts();await loadTrades(new FormData($('#trade-search')).get('q'))}else if(current==='accounts')await loadAccountCards();else if(current==='ledger')await loadEntries();else if(current==='logs')await loadLogs();else if(current==='resources')await loadResources();else if(current==='loadtests')await loadLoadtests();else if(current==='faults')await loadFaults();else if(current==='knowledge')await loadDocuments();else if(current==='assistant')await loadChat()}
function showError(error){if(error.status===401){$('#token-dialog').showModal();return}toast(error.message);if(error.message.includes('无法连接')){$('#connection-error').textContent=error.message;$('#connection-error').hidden=false}}
async function navigate(){clearTimeout(loadPollTimer);clearTimeout(resourcePollTimer);current=location.hash.slice(1) in pages?location.hash.slice(1):'overview';$$('[data-view]').forEach(el=>el.hidden=el.dataset.view!==current);$$('[data-page]').forEach(el=>el.classList.toggle('active',el.dataset.page===current));$('#page-title').textContent=pages[current];try{await refresh()}catch(error){showError(error)}}
function formHandler(id, fn){$(id).addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;if(button)button.disabled=true;try{await fn(new FormData(event.currentTarget))}catch(error){showError(error)}finally{if(button)button.disabled=false}})}
function newKey(){const key='WEB-'+crypto.randomUUID();$('#idempotency-key').value=key;sessionStorage.setItem('trade-key',key)}
$('#idempotency-key').value=sessionStorage.getItem('trade-key')||'WEB-'+crypto.randomUUID();
$('#new-key').addEventListener('click',newKey);
$('#trade-kind').addEventListener('change',()=>{const kind=$('#trade-kind').value;$('#source-field').hidden=['deposit','refund'].includes(kind);$('#target-field').hidden=['withdrawal','refund'].includes(kind);$('#original-field').hidden=kind!=='refund';if(kind==='payment')$('#trade-target').value=accounts.find(a=>a.kind==='merchant')?.id||''});
formHandler('#trade-form',async data=>{const amount=String(data.get('amount'));if(!/^\d+(\.\d{1,2})?$/.test(amount))throw new Error('金额最多保留两位小数');const [whole,fraction='']=amount.split('.');const cents=Number(whole)*100+Number(fraction.padEnd(2,'0'));if(!Number.isSafeInteger(cents)||cents<=0||cents>1e10)throw new Error('金额须大于 0 且不超过 1 亿元');const kind=data.get('kind');const body={kind,amount:cents,source_id:['deposit','refund'].includes(kind)?null:data.get('source_id'),target_id:['withdrawal','refund'].includes(kind)?null:data.get('target_id'),original_id:kind==='refund'?data.get('original_id'):null};const key=data.get('idempotency_key');sessionStorage.setItem('trade-key',key);try{const result=await api('/api/trades',{method:'POST',headers:{'Idempotency-Key':key},body:JSON.stringify(body)});$('#trade-result').className='';$('#trade-result').innerHTML=status(result.status)+(result.replayed?' <span class="tag gray">幂等重放 · 未重复记账</span>':'')+[['交易编号',result.id],['错误码',result.error_code||'无'],['金额','¥ '+money(result.amount)],['Trace ID',result.trace_id]].map(x=>'<div class="result-line"><b>'+x[0]+'</b><span class="code">'+escapeHTML(x[1])+'</span></div>').join('');toast(result.status==='SUCCEEDED'?'交易已成功记账':'交易被业务规则拒绝');}catch(error){$('#trade-result').className='';$('#trade-result').innerHTML='<div class="notice error">'+escapeHTML(error.message)+'</div><pre>'+escapeHTML(JSON.stringify(error.body||{},null,2))+'</pre>';throw error}finally{await loadAccounts();await loadTrades()}});
formHandler('#trade-search',data=>loadTrades(data.get('q')));
formHandler('#account-form',async data=>{await post('/api/accounts',Object.fromEntries(data));$('#account-form').reset();await loadAccountCards();toast('账户已创建')});
formHandler('#log-search',loadLogs);
formHandler('#diagnose-form',async data=>renderDiagnosis(await post('/api/diagnose',{trace_id:data.get('trace_id')||null,minutes:Number(data.get('minutes'))})));
formHandler('#document-form',async data=>{const id=data.get('document_id');data.delete('document_id');const result=await api('/api/documents'+(id?'/'+id:''),{method:id?'PUT':'POST',body:JSON.stringify(Object.fromEntries(data))});$('#document-result').textContent=result.warning||'已保存，建立 '+result.chunks+' 个检索片段';$('#document-form [name=document_id]').value=result.id;await loadDocuments();toast('手册已保存并索引')});
formHandler('#chat-form',async data=>{const question=data.get('question');appendMessage('user',question);$('#chat-form [name=question]').value='';try{const r=await post('/api/chat',{question,session_id:chatSession,include_evidence:data.get('include_evidence')==='on',trace_id:data.get('trace_id')||null});appendMessage('assistant',r.answer+(r.warning?'\n\n'+r.warning:''),r.citations,r.mode)}catch(error){appendMessage('assistant','本次回答未完成：'+error.message);throw error}});
$('#reconcile').addEventListener('click',async()=>{try{const r=await post('/api/reconcile');$('#reconcile-result').innerHTML='<div class="notice '+(r.balanced?'':'error')+'"><b>'+(r.balanced?'账务核对通过':'发现账务差异')+'</b> · '+r.account_count+' 个账户 · '+r.entry_count+' 条分录 · 全账净额 ¥'+money(r.net_balance)+(r.balanced?'':'<pre>'+escapeHTML(JSON.stringify(r,null,2))+'</pre>')+'</div>';await loadEntries()}catch(e){showError(e)}});
$('#clear-document').addEventListener('click',()=>{$('#document-form').reset();$('#document-form [name=document_id]').value='';$('#document-result').textContent=''});
$('#manual-file').addEventListener('change',async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>80000)throw new Error('请导入不超过 80KB 的文本手册');const text=await file.text();if(text.length>20000)throw new Error('手册内容不能超过 20000 字符');$('#document-form [name=content]').value=text;$('#document-form [name=title]').value=file.name.replace(/\.(md|txt)$/i,'');$('#document-form [name=document_id]').value=''}catch(error){showError(error)}});
document.addEventListener('click',async e=>{const button=e.target.closest('button');if(!button)return;try{if(button.dataset.trace){$('#log-search [name=trace_id]').value=button.dataset.trace;location.hash='logs';if(current==='logs')await loadLogs()}if(button.dataset.freeze){await api('/api/accounts/'+button.dataset.freeze+'/freeze',{method:'PUT',body:JSON.stringify({frozen:button.dataset.value==='true'})});await loadAccountCards()}if(button.dataset.startFault){button.disabled=true;await post('/api/faults',{kind:button.dataset.startFault,duration_seconds:Number($('#fault-duration').value),delay_ms:Number($('#fault-delay').value)});await loadFaults();toast('演练已启动，请发送交易观察现象')}if(button.dataset.stopFault){await post('/api/faults/'+button.dataset.stopFault+'/stop');await loadFaults();toast('已停止，新请求不再受该演练影响')}if(button.dataset.editDoc){const d=await api('/api/documents/'+button.dataset.editDoc);for(const field of ['title','version','service','content'])$('#document-form [name='+field+']').value=d[field];$('#document-form [name=document_id]').value=d.id}if(button.dataset.deleteDoc){if(confirm('删除这份手册及其检索索引？')){await api('/api/documents/'+button.dataset.deleteDoc,{method:'DELETE'});await loadDocuments()}}if(button.dataset.question){$('#chat-form [name=question]').value=button.dataset.question;$('#chat-form [name=question]').focus()}if(button.dataset.citation){const hit=citations.get(button.dataset.citation);const container=button.closest('.message');let preview=container.querySelector('.citation-text');if(!preview){preview=document.createElement('div');preview.className='citation-text';container.append(preview)}preview.textContent=hit.title+' · v'+hit.version+' · 第 '+(hit.position+1)+' 段\n'+hit.chunk_id+'\n\n'+hit.text}}catch(error){button.disabled=false;showError(error)}});
$('#refresh').addEventListener('click',()=>refresh().catch(showError));
$('#token-button').addEventListener('click',()=>$('#token-dialog').showModal());
$('#save-token').addEventListener('click',()=>{sessionStorage.setItem('finops-token',$('#token-input').value);setTimeout(initialize,0)});
window.addEventListener('hashchange',navigate);
async function initialize(){try{config=await api('/api/config');$('#db-state').textContent=config.database==='mysql'?'MySQL · 本地实验':'SQLite · 本地实验';$('#index-mode').textContent=config.embedding_configured?'支持混合检索':'关键词索引';$('#chat-mode').textContent=config.model_configured?'模型服务已配置':'知识检索模式';$('#model-help').textContent=config.model_configured?'模型使用检索手册和可选现场证据生成回答，引用原文可点击查看。':'尚未配置模型服务，当前展示检索原文。';await loadAccounts();await navigate()}catch(error){$('#db-state').textContent='服务未连接';showError(error)}}
window.addEventListener('DOMContentLoaded',initialize);
